version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  python:
    build: ./fastapi
    ports:
      - 8080:8080
    container_name: python
    working_dir: /api
    volumes:
      - ../api:/api
    command: [sh, -c, uvicorn main:app --reload --host 0.0.0.0 --port 8080]